### ISSUE TITLE
Getting Error 400: "Changes are sent for review automatically. The query parameter changesNotSentForReview must not be set."

### ISSUE THREAD

**Issue by dbnaza** [angelolloqui/bitrise-step-google-play-rollout-update#3]
Hi there!
In advance, I want to thank you for this plugin!
It is really a time saver!

I've ran into an error when tried to execute it on my published app:
`Traceback (most recent call last):
  File "/tmp/bitrise/step_src/rollout_update.py", line 75, in <module>
    main()
  File "/tmp/bitrise/step_src/rollout_update.py", line 65, in main
    commit_request = service.edits().commit(editId=edit_id, packageName=PACKAGE_NAME, changesNotSentForReview=True).execute()
  File "/root/.local/share/virtualenvs/src/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/.local/share/virtualenvs/src/lib/python3.8/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://androidpublisher.googleapis.com/androidpublisher/v3/applications/com.my.app/edits/12345678:commit?changesNotSentForReview=true&alt=json returned "Changes are sent for review automatically. The query parameter changesNotSentForReview must not be set.". Details: "Changes are sent for review automatically. The query parameter changesNotSentForReview must not be set.">
`

I've forked this project, and changing line 65 to this, worked fine for me:
`commit_request = service.edits().commit(editId=edit_id, packageName=PACKAGE_NAME, changesNotSentForReview=False).execute()`

I'm not sure if this should be the default, but I'll open a pull request with this change. Please, let me know if this makes sense.

Thanks in advance!

**Comment by justindi15** [comment]
Try upgrading from v0.0.1 to v0.02 of this step
